FROM erlang:22

# elixir expects utf8.
ENV ELIXIR_VERSION="v1.12.2" \
	LANG=C.UTF-8

RUN set -xe \
	&& ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz" \
	&& ELIXIR_DOWNLOAD_SHA256="c5affa97defafa1fd89c81656464d61da8f76ccfec2ea80c8a528decd5cb04ad" \
	&& curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL \
	&& mkdir -p /usr/local/src/elixir \
	&& tar -xzC /usr/local/src/elixir --strip-components=1 -f elixir-src.tar.gz \
	&& rm elixir-src.tar.gz \
	&& cd /usr/local/src/elixir \
	&& make install clean \
	&& find /usr/local/src/elixir/ -type f -not -regex "/usr/local/src/elixir/lib/[^\/]*/lib.*" -exec rm -rf {} + \
	&& find /usr/local/src/elixir/ -type d -depth -empty -delete


RUN wget https://nodejs.org/download/release/v14.21.3/node-v14.21.3-linux-arm64.tar.xz
RUN tar -xJf node-v14.21.3-linux-arm64.tar.xz
RUN mkdir -p /usr/local/node
RUN mv ./node-v14.21.3-linux-arm64/* /usr/local/node

ENV NODE_HOME=/usr/local/node
ENV PATH=$PATH:$NODE_HOME/bin

ARG CACHE_EXCHANGE_RATES_PERIOD
ARG DISABLE_READ_API="FASE"
ARG DISABLE_WEBAPP="FALSE"
ARG DISABLE_WRITE_API="FALSE"
ARG CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=""
ARG ADMIN_PANEL_ENABLED=""
ARG CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=""
ARG SESSION_COOKIE_DOMAIN
ARG MIXPANEL_TOKEN
ARG MIXPANEL_URL
ARG AMPLITUDE_API_KEY
ARG AMPLITUDE_URL
ARG RELEASE_VERSION=5.1.4

CMD ["iex"]
